image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup
    before: |
      curl -sfL gpm.simonemms.com | bash

      gpm install helm kubectl pre-commit tfenv yq

      mkdir -p $HOME/.kube

      # Install latest terraform
      tfenv install
      tfenv use

      go install github.com/terraform-docs/terraform-docs@latest

      gp sync-done setup

      pre-commit install --install-hooks -t pre-commit -t commit-msg

      gp sync-done pre-commit

      exit 0
  - name: Hetzner
    command: |
      gp sync-await setup

      if [ -n "${HCLOUD_TOKEN}" ]; then
        echo "Initializing Hetzner"
        if [ -n "${TF_WORKSPACE}" ]; then
          terraform workspace new ${TF_WORKSPACE}
        fi

        make hetzner-init

        gp sync-done hetzner-init
      fi

      exit 0
  - env:
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium
    init: |
      cd ./werft-scraper
      npm ci
    command: |
      gp sync-await setup

vscode:
  extensions:
    - donjayamanne.git-extension-pack
    - EditorConfig.EditorConfig
    - ms-vscode.makefile-tools
    - HashiCorp.terraform
    - HashiCorp.HCL
    - timonwong.shellcheck
