apiVersion: v1
workspace:
  runtime:
    containerdRuntimeDir: /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io # k3s settings
    containerdSocket: /run/k3s/containerd/containerd.sock # k3s settings
    fsShiftMethod: shiftfs # This is only compatible with Ubuntu 20.04 - Ubuntu 22.04 uses cgroup v1
