apiVersion: v1
workspace:
  runtime:
    containerdRuntimeDir: /run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io
    containerdSocket: /run/k3s/containerd/containerd.sock
    fsShiftMethod: shiftfs # This is only compatible with Ubuntu 20.04 - Ubuntu 22.04 uses cgroup v1
