name: Publish installer
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  installer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: browser-actions/setup-chrome@v1

      - run: chrome --version

      - name: Install dependencies
        run: |
          cd ./werft-scraper
          npm ci

      - name: Werft
        run: |
          export PUPPETEER_EXECUTABLE_PATH=$(which chromium)
          node ./werft-scraper

      - name: Create Docker tags
        run: |
          # Get the tag name
          cat ./output.json
          tag=$(cat ./output.json | jq -r '.tags[0]')

          # Pull the tag
          docker pull eu.gcr.io/gitpod-core-dev/build/installer:${tag}

          # Build the nightly
          docker tag eu.gcr.io/gitpod-core-dev/build/installer:${tag} ghcr.io/${{ github.repository }}/installer:nightly
          docker push ghcr.io/${{ github.repository }}/installer:nightly

          # Build today's image
          dateTag=$(date --rfc-3339=date)
          docker tag eu.gcr.io/gitpod-core-dev/build/installer:${tag} ghcr.io/${{ github.repository }}/installer:${dateTag}
          docker push ghcr.io/${{ github.repository }}/installer:${dateTag}
